magephp:
    log_dir: 
        /var/www/html/mageLogs
    environments:
        production:
            ssh:
                port: 22
                flags: -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /var/www/html/deploy/key
                timeout: 60
            user: root
            # branch: main
            from: ./
            host_path: /var/www/my-app
            symlink: laravel
            releases: 10
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
                - ./storage/debugbar
                - ./storage/framework
                - ./storage/logs
            hosts:
                - 139.59.128.168
            pre-deploy:
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
                # - fs/copy: { from: '/var/www/shared/.env', to: '.env' } 
               # - symfony/cache-warmup: { env: 'dev' }
                # - symfony/assets-install: { env: 'dev' }
            on-release:
            post-release:
            post-deploy: