magephp:
    # log_dir: 
    #     /var/www/html/mage-logs
    environments:
        production:
            user: root
            ssh:
                port: 22
                flags: -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@139.59.128.168 -i /var/www/html/deploy
                timeout: 60
            # branch: master
            from: ./
            host_path: /var/www/myapp
            releases: 4
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
                - ./storage/debugbar
                - ./storage/framework
                - ./storage/logs
            hosts:
                - webserver1
                - webserver2
                - webserver3
            pre-deploy:
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
                # - symfony/cache-warmup: { env: 'dev' }
                # - symfony/assets-install: { env: 'dev' }
            on-release:
            post-release:
            post-deploy: